services:
  - type: web
    name: dcj-payroll
    env: php
    plan: free
    buildCommand: ./build.sh
    startCommand: apache2-foreground
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: php_version
        value: 8.2
      - key: NODE_VERSION
        value: 20
    healthCheckPath: /
